// Need to use the React-specific entry point to import `createApi`
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

export interface ApiResponse<T = any> {
  code: number;
  msg: string;
  data: T;
}

export type ListApiResponse<T = any> = ApiResponse<{
  list: T[];
  total: number;
}>;

// Define a service using a base URL and expected endpoints
export const apiSlice = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: 'http://localhost:8080/api/v1' }),
  reducerPath: 'api',
  // Tag types are used for caching and invalidation.
  tagTypes: [],
  endpoints: (build) => ({}),
});

// Hooks are auto-generated by RTK-Query
// Same as `quotesApiSlice.endpoints.getQuotes.useQuery`
export const {} = apiSlice;
