basePath: /api/v1
definitions:
  BadRequest:
    properties:
      code:
        description: 错误码
        format: int32
        type: integer
      msg:
        description: 错误信息
        type: string
    type: object
  domain.AddRequest:
    properties:
      domain:
        type: string
      domain_id:
        type: string
      provider_id:
        type: integer
    type: object
  domain.AddResponse:
    type: object
  domain.DeleteRequest:
    type: object
  domain.DeleteResponse:
    type: object
  domain.Item:
    properties:
      domain:
        type: string
      id:
        type: integer
      provider_name:
        type: string
    type: object
  domain.ListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/domain.Item'
          type: object
        type: array
      total:
        type: integer
    type: object
  domain.QueryItem:
    properties:
      domain:
        type: string
      domain_id:
        type: string
      is_managed:
        type: boolean
      provider_id:
        type: integer
      provider_name:
        type: string
    type: object
  domain.QueryResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/domain.QueryItem'
        type: array
    type: object
  domain.RecordListResponse:
    type: object
  httputils.PageRequest:
    properties:
      order:
        description: Deprecated 请使用方法GetOrder
        type: string
      page:
        description: Deprecated 请使用方法GetPage
        type: integer
      size:
        description: Deprecated 请使用方法GetSize
        type: integer
      sort:
        description: Deprecated 请使用方法GetSort
        type: string
    type: object
  httputils.PageResponse:
    properties:
      list:
        items:
          type: any
        type: array
      total:
        type: integer
    type: object
  provider.CreateProviderRequest:
    properties:
      name:
        type: string
      platform:
        $ref: '#/definitions/provider_entity.Platform'
      secret:
        additionalProperties:
          type: string
        type: object
    type: object
  provider.CreateProviderResponse:
    type: object
  provider.DeleteProviderRequest:
    type: object
  provider.DeleteProviderResponse:
    type: object
  provider.Item:
    properties:
      id:
        type: integer
      name:
        type: string
      platform:
        $ref: '#/definitions/provider_entity.Platform'
    type: object
  provider.ListProviderResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/provider.Item'
          type: object
        type: array
      total:
        type: integer
    type: object
  provider.UpdateProviderRequest:
    properties:
      name:
        type: string
      secret:
        additionalProperties:
          type: string
        type: object
    type: object
  provider.UpdateProviderResponse:
    type: object
  provider_entity.Platform:
    description: |-
      Platform enum type:
      - PlatformCloudflare: cloudflare
      - PlatformTencent: tencent
    enum:
    - cloudflare
    - tencent
    type: string
  user.CurrentUserResponse:
    properties:
      username:
        type: string
    type: object
  user.LoginRequest:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  user.LoginResponse:
    properties:
      username:
        type: string
    type: object
  user.LogoutRequest:
    type: object
  user.LogoutResponse:
    type: object
  user.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    type: object
  user.RefreshTokenResponse:
    properties:
      username:
        type: string
    type: object
  user.RegisterRequest:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  user.RegisterResponse:
    type: object
info:
  title: api文档
  version: "1.0"
paths:
  /domain:
    get:
      consumes:
      - application/json
      description: 获取域名列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/domain.ListResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取域名列表
      tags:
      - domain
    post:
      consumes:
      - application/json
      description: 纳管域名
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/domain.AddRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/domain.AddResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 纳管域名
      tags:
      - domain
  /domain/{id}:
    delete:
      consumes:
      - application/json
      description: 删除域名
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      - in: body
        name: body
        schema:
          $ref: '#/definitions/domain.DeleteRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/domain.DeleteResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 删除域名
      tags:
      - domain
  /domain/{id}/record:
    get:
      consumes:
      - application/json
      description: 获取记录列表
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/domain.RecordListResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取记录列表
      tags:
      - domain/record
  /domain/query:
    get:
      consumes:
      - application/json
      description: 查询域名列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/domain.QueryResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 查询域名列表
      tags:
      - domain
  /provider:
    get:
      consumes:
      - application/json
      description: 获取供应商列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/provider.ListProviderResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取供应商列表
      tags:
      - provider
    post:
      consumes:
      - application/json
      description: 创建供应商
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/provider.CreateProviderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/provider.CreateProviderResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 创建供应商
      tags:
      - provider
  /provider/{id}:
    delete:
      consumes:
      - application/json
      description: 删除供应商
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      - in: body
        name: body
        schema:
          $ref: '#/definitions/provider.DeleteProviderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/provider.DeleteProviderResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 删除供应商
      tags:
      - provider
    put:
      consumes:
      - application/json
      description: 更新供应商
      parameters:
      - in: path
        name: id
        required: true
        type: integer
      - in: body
        name: body
        schema:
          $ref: '#/definitions/provider.UpdateProviderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/provider.UpdateProviderResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 更新供应商
      tags:
      - provider
  /user/current:
    get:
      consumes:
      - application/json
      description: 当前登录用户
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.CurrentUserResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 当前登录用户
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/user.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.LoginResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 登录
      tags:
      - user
  /user/logout:
    delete:
      consumes:
      - application/json
      description: 登出
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/user.LogoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.LogoutResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 登出
      tags:
      - user
  /user/refresh:
    post:
      consumes:
      - application/json
      description: 刷新token
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/user.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.RefreshTokenResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 刷新token
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      description: 注册
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/user.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.RegisterResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 注册
      tags:
      - user
swagger: "2.0"
