basePath: /api/v1
definitions:
  BadRequest:
    properties:
      code:
        description: 错误码
        format: int32
        type: integer
      msg:
        description: 错误信息
        type: string
    type: object
  dns.CreateProviderRequest:
    properties:
      name:
        type: string
      platform:
        $ref: '#/definitions/dns_provider_entity.DnsPlatform'
      secret:
        additionalProperties:
          type: string
        type: object
    type: object
  dns.CreateProviderResponse:
    properties:
      id:
        type: integer
    type: object
  dns.Item:
    properties:
      id:
        type: integer
      name:
        type: string
      platform:
        type: string
    type: object
  dns.ListProviderResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/dns.ProviderItem'
          type: object
        type: array
      total:
        type: integer
    type: object
  dns.ListResponse:
    properties:
      list:
        items:
          $ref: '#/definitions/dns.Item'
          type: object
        type: array
      total:
        type: integer
    type: object
  dns.ProviderItem:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  dns_provider_entity.DnsPlatform:
    description: |-
      DnsPlatform enum type:
      - DnsPlatformCloudflare: cloudflare
      - DnsPlatformDnsPod: dnspod
    enum:
    - cloudflare
    - dnspod
    type: string
  httputils.PageRequest:
    properties:
      order:
        description: Deprecated 请使用方法GetOrder
        type: string
      page:
        description: Deprecated 请使用方法GetPage
        type: integer
      size:
        description: Deprecated 请使用方法GetSize
        type: integer
      sort:
        description: Deprecated 请使用方法GetSort
        type: string
    type: object
  httputils.PageResponse:
    properties:
      list:
        items:
          type: any
        type: array
      total:
        type: integer
    type: object
  user.CurrentUserResponse:
    properties:
      username:
        type: string
    type: object
  user.LoginRequest:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  user.LoginResponse:
    properties:
      username:
        type: string
    type: object
  user.LogoutResponse:
    type: object
  user.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    type: object
  user.RefreshTokenResponse:
    properties:
      username:
        type: string
    type: object
  user.RegisterRequest:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  user.RegisterResponse:
    type: object
info:
  title: api文档
  version: "1.0"
paths:
  /dns:
    get:
      consumes:
      - application/json
      description: 获取dns列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/dns.ListResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取dns列表
      tags:
      - dns
  /dns/provider:
    get:
      consumes:
      - application/json
      description: 获取dns提供商列表
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/dns.ListProviderResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 获取dns提供商列表
      tags:
      - dns/provider
    post:
      consumes:
      - application/json
      description: 创建dns提供商
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/dns.CreateProviderRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/dns.CreateProviderResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 创建dns提供商
      tags:
      - dns/provider
  /user/current:
    get:
      consumes:
      - application/json
      description: 当前登录用户
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.CurrentUserResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 当前登录用户
      tags:
      - user
  /user/login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/user.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.LoginResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 登录
      tags:
      - user
  /user/logout:
    get:
      consumes:
      - application/json
      description: 登出
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.LogoutResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 登出
      tags:
      - user
  /user/refresh:
    post:
      consumes:
      - application/json
      description: 刷新token
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/user.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.RefreshTokenResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 刷新token
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      description: 注册
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/user.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            properties:
              code:
                type: integer
              data:
                $ref: '#/definitions/user.RegisterResponse'
              msg:
                type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/BadRequest'
      summary: 注册
      tags:
      - user
swagger: "2.0"
