name: Docker

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  APP_NAME: ${{ github.event.repository.name }}
  NAMESPACE: app
  REGISTRY: ${{ secrets.DOCKER_REGISTRY && secrets.DOCKER_REGISTRY || 'docker.io' }}
  REPOSITORY: ${{ github.repository }}
  IMAGE_LATEST_TAG: ${{ startsWith(github.ref, 'refs/tags/') && 'latest' || 'main' }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set environment variables
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          VERSION_TAG=${GITHUB_REF#refs/tags/}
        else
          VERSION_TAG=${IMAGE_LATEST_TAG}-${COMMIT_ID::7}
        fi

        echo "VERSION_TAG=${VERSION_TAG}" >> $GITHUB_ENV

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Mkdir
      run: |
        mkdir -p ./frontend/dist
        echo "" > ./frontend/dist/index.html

    - name: Lint
      uses: golangci/golangci-lint-action@v6

    - name: Tests
      run: |
        go test $(go list ./...)

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Docker build and push
      uses: docker/build-push-action@v5
      with:
        platforms: |
          linux/amd64,linux/arm,linux/arm64
        push: true
        file: Dockerfile
        tags: codfrm/dns-kit:${{ env.IMAGE_LATEST_TAG }},codfrm/dns-kit:${{ env.VERSION_TAG }}
        context: .
        build-args: |
          APP_VERSION=${{ env.VERSION_TAG }}

